/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
  const ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
  const ElSlider: typeof import('element-plus/es')['ElSlider']
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
  const ElUpload: typeof import('element-plus/es')['ElUpload']
}
