// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
  const ElUpload: typeof import('element-plus/es')['ElUpload']
}
export {}
