/*
 * @Description: 自动导入声明文件
 * @Version: 1.0.0
 * @Autor: qsyj
 * @Date: 2022-03-14 13:55:04
 * @LastEditors: qsyj
 * @LastEditTime: 2022-03-14 13:55:27
 * @FilePath: \vite-admin-vue\auto-imports.d.ts
 */

// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {}
export {}
