# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "docs" ]
  pull_request:
    branches: [ "docs" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
        # cache: "pnpm"
    - name: Install PNPM
      run: npm i -g pnpm

    - name: Install deps
      run: pnpm install

    - name: Build
      run: pnpm run docs:build

    - name: Upload Docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        TOKEN: ${{ secrets.QSYJ_BUIL_UPLOAD }}
        BRANCH: gh-pages
        FOLDER: docs
